// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnnXLvMoy3aUvVy4X5D0DbNlbVSxe4SgY',
    appId: '1:507394330580:web:099bd5ad2ae2a770bd5041',
    messagingSenderId: '507394330580',
    projectId: 'todoapp-1f6c3',
    authDomain: 'todoapp-1f6c3.firebaseapp.com',
    storageBucket: 'todoapp-1f6c3.appspot.com',
    measurementId: 'G-39RQMK83S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq0QSptwhg6J-kG1TVweLKLTMfeQLk2cc',
    appId: '1:507394330580:android:14ec18e092477eb4bd5041',
    messagingSenderId: '507394330580',
    projectId: 'todoapp-1f6c3',
    storageBucket: 'todoapp-1f6c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbntT4pyv0MdFGj_9cPj9LaFn67IrVcis',
    appId: '1:507394330580:ios:c549a44acb04ddc6bd5041',
    messagingSenderId: '507394330580',
    projectId: 'todoapp-1f6c3',
    storageBucket: 'todoapp-1f6c3.appspot.com',
    iosBundleId: 'com.example.todoUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbntT4pyv0MdFGj_9cPj9LaFn67IrVcis',
    appId: '1:507394330580:ios:c549a44acb04ddc6bd5041',
    messagingSenderId: '507394330580',
    projectId: 'todoapp-1f6c3',
    storageBucket: 'todoapp-1f6c3.appspot.com',
    iosBundleId: 'com.example.todoUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnnXLvMoy3aUvVy4X5D0DbNlbVSxe4SgY',
    appId: '1:507394330580:web:beb75747a4b686abbd5041',
    messagingSenderId: '507394330580',
    projectId: 'todoapp-1f6c3',
    authDomain: 'todoapp-1f6c3.firebaseapp.com',
    storageBucket: 'todoapp-1f6c3.appspot.com',
    measurementId: 'G-94NX9XW663',
  );
}
